### ISSUE TITLE
Repeating actions after clicking in Autorun checkbox

### ISSUE THREAD

**Issue by setzerbomb** [zcapper/CSharp-Macro-Mouse-Clicker#4]
**Changes Proposed**

Autorun checkbox is not repeating actions in an indefinite way, the expected behaviour would be execute all the actions over and over again until some event (mouse or keyboard) happens.

I solved this issue by adding an event listener for a double right click event.

This is the  [forked repo](https://github.com/setzerbomb/CSharp-Macro-Mouse-Clicker/tree/repeat-actions), hope that you see and approve a PR.

**Comment by zcapper** [comment]
Hi!

Thanks for raising this. I think the Esc key would make the most sense for cancelling a macro, but regardless I'm happy to accept your changes as they definitely are an improvement.

Cheers
